name: private_markdown_writer
description: An private markdown writer running on web, (and maybe android, ios)

publish_to: 'none'

version: 0.1.3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.1.3
  state_notifier: ^0.7.2+1
  freezed_annotation: ^2.2.0
  flutter_markdown: ^0.6.13+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  url_launcher: ^6.1.8
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  pedantic_mono: ^1.21.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  hive_generator: ^2.0.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
      - assets/images/
  generate: true
