name: private_markdown_writer
description: An private markdown writer running on web, (and maybe android, ios)

publish_to: 'none'

version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: any
  state_notifier: any
  freezed_annotation: any
  flutter_markdown: any
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  url_launcher: ^6.1.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  pedantic_mono:
  build_runner:
  freezed:
  json_serializable:
  mockito:
  hive_generator: ^2.0.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
      - assets/images/
  generate: true
